include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_declarations
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - unnecessary_const
    - prefer_single_quotes

formatter:
  page_width: 100
  trailing_commas: preserve